### ISSUE TITLE
ModuleNotFoundError: No module named 'petrelbox'

### ISSUE THREAD

**Issue by matabear-wyx** [OpenGVLab/Hulk#6]
Traceback (most recent call last):
  File "/mnt/data/yuxiong/Hulk/experiments/release/../..//test_mae.py", line 9, in <module>
    from core.testers import tester_entry
  File "/mnt/data/yuxiong/Hulk/core/testers/__init__.py", line 1, in <module>
    from ..solvers.solver_mae_devnew import TesterMAEDev
  File "/mnt/data/yuxiong/Hulk/core/solvers/__init__.py", line 3, in <module>
    from .solver_mae_devnew import SolverMAEDev
  File "/mnt/data/yuxiong/Hulk/core/solvers/solver_mae_devnew.py", line 40, in <module>
    from core.solvers.utils.peddet_tester_dev import PedDetMAEEvaluator
  File "/mnt/data/yuxiong/Hulk/core/solvers/utils/peddet_tester_dev.py", line 28, in <module>
    from petrelbox.io import PetrelHelper
ModuleNotFoundError: No module named 'petrelbox'

pip/conda install petrelbox doesn't work, I was trying to do the evaluation, pls provide an alternative way

**Comment by Cohesion97** [comment]
Sorry for that. 

I have now removed the requirement of petrelbox during the evaluation of the pedestrian detection task.
